{"name":"mi-backend-app","hostname":"LAPTOP-18E04BK2","pid":11160,"level":50,"msg":"Ingreso a un ruta que no existe","time":"2025-09-06T05:28:29.157Z","v":0}
{"name":"mi-backend-app","hostname":"LAPTOP-18E04BK2","pid":11160,"level":50,"msg":"Ingreso a un ruta que no existe","time":"2025-09-06T05:28:29.183Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":12700,"level":50,"msg":"❌ Error al iniciar servidor: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.createTable (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:229:12)\n    at async Function.sync (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1353:7)\n    at async Sequelize.sync (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async syncDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\models\\index.ts:12:5)\n    at async initDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:23:5)\n    at async startServer (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:28:9) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: No database selected\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_NO_DB_ERROR',\n    errno: 1046,\n    sqlState: '3D000',\n    sqlMessage: 'No database selected',\n    sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n    parameters: undefined\n  },\n  original: Error: No database selected\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_NO_DB_ERROR',\n    errno: 1046,\n    sqlState: '3D000',\n    sqlMessage: 'No database selected',\n    sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n    parameters: undefined\n  },\n  sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n  parameters: {}\n}","time":"2025-09-12T00:34:58.696Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":7824,"level":50,"msg":"❌ Error al iniciar servidor: ConnectionError [SequelizeConnectionError]: Unknown database 'tu_base_de_datos_aqui'\n    at ConnectionManager.connect (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:126:17)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at async C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32\n    at async ConnectionManager.getConnection (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:280:7)\n    at async C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:638:26\n    at async MySQLQueryInterface.tableExists (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:242:17)\n    at async Function.sync (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1349:21)\n    at async Sequelize.sync (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async syncDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\models\\index.ts:12:5) {\n  parent: Error: Unknown database 'tu_base_de_datos_aqui'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at ClientHandshake.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_DB_ERROR',\n    errno: 1049,\n    sqlState: '42000',\n    sqlMessage: \"Unknown database 'tu_base_de_datos_aqui'\",\n    sql: undefined\n  },\n  original: Error: Unknown database 'tu_base_de_datos_aqui'\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at ClientHandshake.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_BAD_DB_ERROR',\n    errno: 1049,\n    sqlState: '42000',\n    sqlMessage: \"Unknown database 'tu_base_de_datos_aqui'\",\n    sql: undefined\n  }\n}","time":"2025-09-12T00:36:36.895Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":2368,"level":50,"msg":"❌ Error al iniciar servidor: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.createTable (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:229:12)\n    at async Function.sync (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1353:7)\n    at async Sequelize.sync (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async syncDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\models\\index.ts:12:5)\n    at async initDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:23:5)\n    at async startServer (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:28:9) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: No database selected\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_NO_DB_ERROR',\n    errno: 1046,\n    sqlState: '3D000',\n    sqlMessage: 'No database selected',\n    sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n    parameters: undefined\n  },\n  original: Error: No database selected\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_NO_DB_ERROR',\n    errno: 1046,\n    sqlState: '3D000',\n    sqlMessage: 'No database selected',\n    sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n    parameters: undefined\n  },\n  sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n  parameters: {}\n}","time":"2025-09-12T00:37:04.492Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":8412,"level":50,"msg":"❌ Error al iniciar servidor: Error\n    at Query.run (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\query.js:46:25)\n    at C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:650:28\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async MySQLQueryInterface.createTable (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\query-interface.js:229:12)\n    at async Function.sync (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:1353:7)\n    at async Sequelize.sync (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:825:9)\n    at async syncDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\models\\index.ts:12:5)\n    at async initDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:23:5)\n    at async startServer (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:28:9) {\n  name: 'SequelizeDatabaseError',\n  parent: Error: No database selected\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_NO_DB_ERROR',\n    errno: 1046,\n    sqlState: '3D000',\n    sqlMessage: 'No database selected',\n    sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n    parameters: undefined\n  },\n  original: Error: No database selected\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at Query.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_NO_DB_ERROR',\n    errno: 1046,\n    sqlState: '3D000',\n    sqlMessage: 'No database selected',\n    sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n    parameters: undefined\n  },\n  sql: \"CREATE TABLE IF NOT EXISTS `users` (`id` CHAR(36) BINARY NOT NULL , `name` VARCHAR(255) NOT NULL, `lastname` VARCHAR(255) NOT NULL, `dni` VARCHAR(255) NOT NULL UNIQUE, `email` VARCHAR(255) NOT NULL UNIQUE, `password` VARCHAR(255) NOT NULL, `rol` ENUM('admin', 'user', 'professional') NOT NULL DEFAULT 'user', `created_at` DATETIME NOT NULL, `updated_at` DATETIME NOT NULL, PRIMARY KEY (`id`)) ENGINE=InnoDB;\",\n  parameters: {}\n}","time":"2025-09-12T00:38:23.887Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":15356,"level":50,"msg":"❌ Error al crear la base de datos: AccessDeniedError [SequelizeAccessDeniedError]: Access denied for user 'admin'@'190.49.41.182' (using password: YES)\n    at ConnectionManager.connect (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:118:17)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at async C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32\n    at async ConnectionManager.getConnection (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:280:7)\n    at async C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:638:26\n    at async createDatabaseIfNotExists (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\db.ts:19:5)\n    at async initDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:22:5)\n    at async startServer (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:30:9) {\n  parent: Error: Access denied for user 'admin'@'190.49.41.182' (using password: YES)\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at ClientHandshake.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_ACCESS_DENIED_ERROR',\n    errno: 1045,\n    sqlState: '28000',\n    sqlMessage: \"Access denied for user 'admin'@'190.49.41.182' (using password: YES)\",\n    sql: undefined\n  },\n  original: Error: Access denied for user 'admin'@'190.49.41.182' (using password: YES)\n      at Packet.asError (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packets\\packet.js:740:17)\n      at ClientHandshake.execute (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\commands\\command.js:29:26)\n      at Connection.handlePacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:475:34)\n      at PacketParser.onPacket (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:93:12)\n      at PacketParser.executeStart (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\packet_parser.js:75:16)\n      at Socket.<anonymous> (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\mysql2\\lib\\base\\connection.js:100:25)\n      at Socket.emit (node:events:518:28)\n      at Socket.emit (node:domain:489:12)\n      at addChunk (node:internal/streams/readable:561:12)\n      at readableAddChunkPushByteMode (node:internal/streams/readable:512:3) {\n    code: 'ER_ACCESS_DENIED_ERROR',\n    errno: 1045,\n    sqlState: '28000',\n    sqlMessage: \"Access denied for user 'admin'@'190.49.41.182' (using password: YES)\",\n    sql: undefined\n  }\n}","time":"2025-09-16T23:08:51.918Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":7860,"level":50,"msg":"❌ Error al crear la base de datos: HostNotFoundError [SequelizeHostNotFoundError]: getaddrinfo ENOTFOUND database1-1.cnovprkat6rf.us-east-1.rds.amazonaws.com\n    at ConnectionManager.connect (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\mysql\\connection-manager.js:120:17)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async ConnectionManager._connect (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:332:24)\n    at async C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:250:32\n    at async ConnectionManager.getConnection (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\dialects\\abstract\\connection-manager.js:280:7)\n    at async C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\sequelize.js:638:26\n    at async createDatabaseIfNotExists (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\db.ts:19:5)\n    at async initDatabase (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:22:5)\n    at async startServer (C:\\proyectos\\Backend-Proyecto-Integrador\\server.ts:30:9) {\n  parent: Error: getaddrinfo ENOTFOUND database1-1.cnovprkat6rf.us-east-1.rds.amazonaws.com\n      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26) {\n    errno: -3008,\n    code: 'ENOTFOUND',\n    syscall: 'getaddrinfo',\n    hostname: 'database1-1.cnovprkat6rf.us-east-1.rds.amazonaws.com',\n    fatal: true\n  },\n  original: Error: getaddrinfo ENOTFOUND database1-1.cnovprkat6rf.us-east-1.rds.amazonaws.com\n      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:122:26) {\n    errno: -3008,\n    code: 'ENOTFOUND',\n    syscall: 'getaddrinfo',\n    hostname: 'database1-1.cnovprkat6rf.us-east-1.rds.amazonaws.com',\n    fatal: true\n  }\n}","time":"2025-09-16T23:09:36.193Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-EFC8Q3O","pid":15556,"level":50,"msg":"Error al crear usuario: ValidationError [SequelizeValidationError]: Validation error: La contraseña debe tener al menos 6 caracteres\n    at InstanceValidator._validate (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async InstanceValidator._validateAndRunHooks (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\instance-validator.js:111:7)\n    at async InstanceValidator.validate (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\instance-validator.js:93:12)\n    at async User.save (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:4077:7)\n    at async Function.create (C:\\proyectos\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:2305:12)\n    at async UserRepository.create (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\repositories\\userRepository.ts:7:16)\n    at async UserService.createUser (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\services\\userService.ts:10:25)\n    at async UserController.createUser (C:\\proyectos\\Backend-Proyecto-Integrador\\src\\controllers\\userController.ts:16:29) {\n  errors: [\n    ValidationErrorItem {\n      message: 'La contraseña debe tener al menos 6 caracteres',\n      type: 'Validation error',\n      path: 'password',\n      value: '32123',\n      origin: 'FUNCTION',\n      instance: [User],\n      validatorKey: 'len',\n      validatorName: 'len',\n      validatorArgs: [Array],\n      original: [Error]\n    }\n  ]\n}","time":"2025-09-27T00:07:10.245Z","v":0}
{"name":"mi-backend-app","hostname":"DESKTOP-CVE24LS","pid":14368,"level":50,"msg":"Error al crear usuario: ValidationError [SequelizeValidationError]: notNull Violation: User.lastname cannot be null,\nnotNull Violation: User.dni cannot be null,\nnotNull Violation: User.email cannot be null,\nnotNull Violation: User.password cannot be null\n    at InstanceValidator._validate (C:\\Users\\Sergio\\Desktop\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\instance-validator.js:78:13)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async InstanceValidator._validateAndRunHooks (C:\\Users\\Sergio\\Desktop\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\instance-validator.js:111:7)\n    at async InstanceValidator.validate (C:\\Users\\Sergio\\Desktop\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\instance-validator.js:93:12)\n    at async User.save (C:\\Users\\Sergio\\Desktop\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:4077:7)\n    at async Function.create (C:\\Users\\Sergio\\Desktop\\Backend-Proyecto-Integrador\\node_modules\\sequelize\\src\\model.js:2305:12)\n    at async create (C:\\Users\\Sergio\\Desktop\\Backend-Proyecto-Integrador\\src\\repositories\\userRepository.ts:7:12)\n    at async createUser (C:\\Users\\Sergio\\Desktop\\Backend-Proyecto-Integrador\\src\\services\\userService.ts:7:21)\n    at async createUser (C:\\Users\\Sergio\\Desktop\\Backend-Proyecto-Integrador\\src\\controllers\\userController.ts:13:25) {\n  errors: [\n    ValidationErrorItem {\n      message: 'User.lastname cannot be null',\n      type: 'notNull Violation',\n      path: 'lastname',\n      value: null,\n      origin: 'CORE',\n      instance: [User],\n      validatorKey: 'is_null',\n      validatorName: null,\n      validatorArgs: []\n    },\n    ValidationErrorItem {\n      message: 'User.dni cannot be null',\n      type: 'notNull Violation',\n      path: 'dni',\n      value: null,\n      origin: 'CORE',\n      instance: [User],\n      validatorKey: 'is_null',\n      validatorName: null,\n      validatorArgs: []\n    },\n    ValidationErrorItem {\n      message: 'User.email cannot be null',\n      type: 'notNull Violation',\n      path: 'email',\n      value: null,\n      origin: 'CORE',\n      instance: [User],\n      validatorKey: 'is_null',\n      validatorName: null,\n      validatorArgs: []\n    },\n    ValidationErrorItem {\n      message: 'User.password cannot be null',\n      type: 'notNull Violation',\n      path: 'password',\n      value: null,\n      origin: 'CORE',\n      instance: [User],\n      validatorKey: 'is_null',\n      validatorName: null,\n      validatorArgs: []\n    }\n  ]\n}","time":"2025-10-09T01:36:58.432Z","v":0}
